-- MySQL Script generated by MySQL Workbench
-- Mon Oct  7 19:00:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyectobiodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyectobiodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyectobiodb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `proyectobiodb` ;

-- -----------------------------------------------------
-- Table `proyectobiodb`.`mediciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectobiodb`.`mediciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medida` DECIMAL(10,2) NOT NULL,
  `lugar` VARCHAR(255) NOT NULL,
  `tipo_gas` VARCHAR(100) NOT NULL,
  `hora` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
